# docker-compose.yml文件的版本
version: "3"
# 管理的服务
services:
  mydb:
    image: postgres:11
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_DB: natrium
      POSTGRES_PASSWORD: eogbperqwdm
    ports:
      - "5432:5432"
    restart:
      always